Rename %s/ruby/php/g

diff --git a/bin/phpenv-each b/bin/phpenv-each
--- a/bin/phpenv-each
+++ b/bin/phpenv-each
@@ -3,8 +3,8 @@
 verbose=0
 
 function usage() {
-  echo >&2 "Usage: rbenv each [-v] ..."
-  echo >&2 "       -v Verbose mode. Prints a header for each ruby."
+  echo >&2 "Usage: phpenv each [-v] ..."
+  echo >&2 "       -v Verbose mode. Prints a header for each php."
 }
 while getopts vh option
 do	case "$option" in
@@ -17,23 +17,23 @@ do	case "$option" in
 done
 shift $(($OPTIND-1))
 
-failed_rubies=""
+failed_phps=""
 
-for ruby in `rbenv versions --bare`; do
+for php in `phpenv versions --bare`; do
   if [ $verbose = 1 ]; then
-    echo -e "\033[1;34m[$ruby]:\033[0m \033[1;32m$@\033[0m";
+    echo -e "\033[1;34m[$php]:\033[0m \033[1;32m$@\033[0m";
     echo -e "\033[1;34m******************************************************************\033[0m";
   fi
-  RBENV_VERSION=$ruby "$@"
+  PHPENV_VERSION=$php "$@"
   if [ $verbose = 1 ]; then
     echo
   fi
   if [ $? != 0 ]; then
-    failed_rubies="$failed_rubies $ruby"
+    failed_phps="$failed_phps $php"
   fi
 done
 
-if [ -n "$failed_rubies" ]; then
-  echo -e "\033[1;31mFAILED IN:$failed_rubies\033[0m"
+if [ -n "$failed_phps" ]; then
+  echo -e "\033[1;31mFAILED IN:$failed_phps\033[0m"
 fi
 
